### ISSUE TITLE
vmkdir -p does not do anything

### ISSUE THREAD

**Issue by sfabbro** [canfar/vos#66]
vmkdir does not seem to create directories as required:

$ vmkdir -p vos:sfabbro/toto/tata
$ vls vos:sfabbro/toto/tata
ERROR vls [Errno 2] NodeNotFound: vos://cadc.nrc.ca!vospace/sfabbro/toto/tata
$ vmkdir -h | grep -- -p
  -p                   Create intermediate directories as required.

**Comment by ijiraq** [comment]
Please let user know that a new release was pushed to PyPI.

JJ
